title: twOday
description: Hacker is the new sexy
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker

#markdown
markdown: kramdown

## twOday
author: twOday
organization: www.kugou.com
organization_url: http://www.kugou.com
github_username: 37du
location: GuangZhou, China
email: 